### ISSUE TITLE
PRNG not seeded.

### ISSUE THREAD

**Issue by hasyimibhar** [perlin-network/wavelet#143]
Wavelet uses the default source from `math/rand` package, which is [not seeded by default](https://golang.org/pkg/math/rand/). I looked through the source code and I don't see it being seeded anywhere. Not sure if this is intended or not.

**Comment by iwasaki-kenta** [comment]
It is not seeded by default; there's no specific intention as to why.

**Comment by hasyimibhar** [comment]
I don't think there will be any issues if it's not seeded. As long as the randomness is uniform, Wavelet should work.

Just wondering if it's intentional, because in my experience, when PRNG is used in production, it's usually seeded. Not seeding it (i.e. seeding it with the same value) is usually done for testing purposes.

**Comment by iwasaki-kenta** [comment]
> I don't think there will be any issues if it's not seeded. As long as the randomness is uniform, Wavelet should work.
> 
> Just wondering if it's intentional, because in my experience, when PRNG is used in production, it's usually seeded. Not seeding it (i.e. seeding it with the same value) is usually done for testing purposes.

Gotcha, I usually see the opposite. To make sure tests are deterministic, the PRNG is seeded. In production, there is no necessity to seed it.

**Comment by a-urth** [comment]
Is there any resolution to that? Should we seed `rand` for other than tests usage?

**Comment by iwasaki-kenta** [comment]
Not seeding is fine.
