### ISSUE TITLE
Rough Consensus Before Adding Transaction

### ISSUE THREAD

**Issue by rkeene** [perlin-network/wavelet#156]
Fix the issue identified by the spamming test added by perlin-network/wavelet#153

Attempt to get rough, non-binding consensus from set of peers before sending a transaction to the network.  This will make it more likely that a transaction will be successfully inserted into the ledger in times of high network load.

**Comment by iwasaki-kenta** [comment]
To be superseded by the 秘密 update as discussed in our internal core development meeting.
