### ISSUE TITLE
Contract call fails with `insufficient gas` even though contract has sufficient gas deposited

### ISSUE THREAD

**Issue by ryanswart** [perlin-network/wavelet#160]
When I call a contract function that will take 700k PERL gas, on a contract that has 100mil PERL gas deposited, from a wallet with 500k PERLs, with a 1 PERL gas limit, I get an "insufficient gas" error, the wallet pays 2 PERLS in transaction fees, and the contract's gas deposit balance stays the same.

When I call the same function from a wallet with 100mil PERLs, it executes successfully, deducts gas from the contract's gas balance, and only deducts the 2 PERL transaction fee from the wallet's balance.

It is expected that when the contract pays the gas fees, the calling wallet account does not have to have enough PERLs to theoretically pay the gas fees. This allows users to run expensive contracts without needing a large amount of PERLs in their wallet.

**Comment by iwasaki-kenta** [comment]
Issue was not able to be reproduced by @hasyimibhar and @a-urth. Closing until we are able to reproduce the issue.
