### ISSUE TITLE
Implement generics for Snowball and LRU.

### ISSUE THREAD

**Issue by a-urth** [perlin-network/wavelet#182]
Currently snowball used for dealing with two entities - rounds for finalization and just bools for determining whether node is out of sync.
Generic approach at the moment is to store in snowball entity which implements interface to get its id (to store it in the map).
Better approach might be used, maybe code generation, maybe something else.

**Comment by iwasaki-kenta** [comment]
To further mitigate safety/liveness issues by the way, there are more changes I, @rkeene and @losfair propose to append to Snowball that may only apply w.r.t. Wavelet's DAG and consensus round structure.

One huge improvement is to allow for nodes to overwrite their preferred round decision based on the contents of said round.

A node may choose to overwrite their preferred round if:
1. Some round that is valid and collapsible has an ending critical transaction that is at a lower depth than the node's current preferred round's ending critical transaction depth.
2. Some round that is valid and collapsible encompasses a larger number of ancestral transactions from it's round's ending critical transaction.

Another improvement that may be made is to improve the ordering of transactions for a round. Currently, we perform a BFS over all transactions from the rounds ending transaction.

Instead, to enforce an ordering, after discovering the ancestry of a consensus round, we should sort the transactions by depth and lexicographical ordering by their transaction IDs, and then proceed to apply them to the ledger.

This enforces the DAG structure to enforce a more linear, topological graph ordering in which transactions are applied to the ledger.

**Comment by AhmadMuzakkir** [comment]
Potential code gen library https://github.com/cheekybits/genny.

**Comment by iwasaki-kenta** [comment]
Will extend this PR to in general be work on implement generics for both Snowball and LRU modules. Assigning @AhmadMuzakkir to this task.

**Comment by iwasaki-kenta** [comment]
PR is ready at #226.
