### ISSUE TITLE
Connect/disconnect/restart API and CLI methods.

### ISSUE THREAD

**Issue by rkeene** [perlin-network/wavelet#185]
Create Disconnect and Connect API and CLI Methods.

CLI: `/connect <host> [<port>]`
CLI: `/disconnect <host> [<port>]`
CLI: `/restart <--hard>`
API: `/node/connect/<:host>[/<:port>]`
API: `/node/disconnect/<:host>[/<:port>]`
API: `/node/restart?hard=true`

For Connect calls: port missing, use configured port
For Disconnect calls: port missing, match any port (disconnect all if multiple matches)

**Comment by iwasaki-kenta** [comment]
Finished `connect` and `disconnect` commands, and pushed directly to `master`.

**Comment by iwasaki-kenta** [comment]
Assigned @a-urth. For `restart`, passing in a `--hard` flag either in the CLI or via the HTTP API will flush/delete the node's persisted database on-disk.

The node will be restarted via the method specified in recovery.go, where the node is first shut down then restarted.

**Comment by a-urth** [comment]
From issue description it seems that `port` should be optional parameter, but in `cli` its implemented as mandatory.
@rkeene @iwasaki-kenta so should it be optional? and if yes, what value should be used as default?

**Comment by iwasaki-kenta** [comment]
> From issue description it seems that `port` should be optional parameter, but in `cli` its implemented as mandatory.
> @rkeene @iwasaki-kenta so should it be optional? and if yes, what value should be used as default?

Port should be made mandatory for `connect`. However for `disconnect`, we should allow for the specification of something like a regex to match addresses.

**Comment by a-urth** [comment]
also, in examples @rkeene marked host and post as url parts, but i think its better to make those first of all as `POST` request, then make host+port a single value and move it to json payload. so it will be consistent with `cli` and there will be no problems with special characters when we'll add regexp for disconnect.
what do you think guys @rkeene @iwasaki-kenta ?
