### ISSUE TITLE
Allow for node-local params to be set dynamically.

### ISSUE THREAD

**Issue by iwasaki-kenta** [perlin-network/wavelet#190]
Parameters such as:

- SNOWBALL_K
- SNOWBALL_ALPHA
- SNOWBALL_BETA
- All network-related timeouts
- SYNC_CHUNK_SIZE
- MAX_DOWNLOAD_DEPTH_DIFF
- SYNC_IF_ROUNDS_DIFFER_BY
- PRUNING_LIMIT

... should be configurable in real-time via CLI.

**Comment by a-urth** [comment]
Updating pruning limit might be not that easy, since it affects buffer size and logic within `Rounds` object.
