### ISSUE TITLE
Investigate Contract Spawning Costs

### ISSUE THREAD

**Issue by rkeene** [perlin-network/wavelet#191]
Currently spawning many contracts quickly uses a lot of CPU, investigate why

**Comment by AhmadMuzakkir** [comment]
CPU profile while spawning the contracts.

![image](https://user-images.githubusercontent.com/10398517/63953751-83764100-cab4-11e9-97df-9bf5f65b6eb9.png)

**Comment by a-urth** [comment]
Looking at the flame graph I can say that its pretty much the same as with profile of calling smart contract. And aside of grpc/http side its mostly hashes (blake2b and edwards) computation, snappy compression and wasm vm spawn.
I guess maybe hex decode can be tackled, to use some more efficient approach. Other than that most of the parts already were addressed =/

**Comment by AhmadMuzakkir** [comment]
I'll take a look at the `sendTransactionRequest.bind` to see if there're improvements to be made.

**Comment by iwasaki-kenta** [comment]
`validateWasm` is the biggest contender for the latency - @AhmadMuzakkir please do provide a flamegraph on `sendTransaction` as well. If it can be improved, that would assist with performance generally.

**Comment by iwasaki-kenta** [comment]
The new update to Life which changes wasm module code validation semantics speeds up contract spawning by 7x.
