### ISSUE TITLE
Code cleanup on tx_applier.go.

### ISSUE THREAD

**Issue by iwasaki-kenta** [perlin-network/wavelet#193]
From the looks of things, it seems that a code cleanup needs to be in order for tx_applier.go.

https://github.com/perlin-network/wavelet/blob/05cdfa233c94f164f00339f0f7728948b252c712/tx_applier.go#L31-L46

There are three separate structs that I believe either may be merged into one, or otherwise ridden off. This'll help reduce some memory allocations alongside the hot paths of applying transactions to the ledger state.

Low priority for the time being, but definitely something necessary.

**Comment by AhmadMuzakkir** [comment]
To reduce memory allocations and loops, we can replace ApplyContext.States() with `Iterate(callback func(contractID AccountID, state *VMState))`

https://github.com/perlin-network/wavelet/blob/05cdfa233c94f164f00339f0f7728948b252c712/tx_applier.go#L66-L76

to

```go
func (ac *ApplyContext) Iterate(callback func(contractID AccountID, vm *VMState)) {
	states := make([]*state, 0, len(ac.contractIDs))
	for _, id := range ac.contractIDs {
                callback(id, ac.contractVMStates[id])
	}
}
```

and

https://github.com/perlin-network/wavelet/blob/459950c1720361bd877e69148c934e510a67b4e2/collapse.go#L275-L278

to

```go
applyCtx.Iterate(func(contractID AccountID, vm *VMState) {
	SaveContractMemorySnapshot(res.snapshot, contractID, vm)
	SaveContractGlobals(res.snapshot, contractID, vm)
})
```

**Comment by iwasaki-kenta** [comment]
Basically just:

```go
for _, id := range ctx.ContractIDs {
    SaveContractMemoryGlobalSnapshot(res.snapshot, id, ctx.ContractVMs[id].Memory)
    SaveContractGlobals(res.snapshot, id, ctx.ContractVMs[id].Globals)
}
```

Right?
