### ISSUE TITLE
Bug in JSON parser for transaction

### ISSUE THREAD

**Issue by hasyimibhar** [perlin-network/wavelet#206]
There's a minor bug here: https://github.com/perlin-network/wavelet/blob/master/tx_json.go#L288-L292

Also, it's a good idea to write proper tests for the functions in `tx_json.go`.

**Comment by iwasaki-kenta** [comment]
Actually, the package could be cleaned up a bit. We could have MarshalJSON/UnmarshalJSON and Marshal/Unmarshal (bytes) to each individual transaction type (Nop, Transfer, Stake, Contract, Batch) and remove tx_json.go entirely.

**Comment by iwasaki-kenta** [comment]
Fixed it here: https://github.com/perlin-network/wavelet/commit/3f3334c525015955ceed4c1de0535173636dbe32
