### ISSUE TITLE
Add a way to get pprof stats from a running node

### ISSUE THREAD

**Issue by rkeene** [perlin-network/wavelet#209]
One option is to create a CLI command to dump a pprof heap and goroutine dump -- pretty much the same as we do when our max memory detector is invoked in `recovery.go`.

Another option is to expose pprof over the HTTP API (but this may be subject to abuse, rate-limiting may be enough though)

**Comment by a-urth** [comment]
I think we already exposed `pprof` by default
https://github.com/perlin-network/wavelet/blob/master/cmd/wavelet/main.go#L51

**Comment by rkeene** [comment]
Excellent -- I didn't realize that had the side-effect of adding handlers to the HTTP object... Now we should restrict access to that API ! 😄
