### ISSUE TITLE
Build fails on 32 bit architecture

### ISSUE THREAD

**Issue by jakerr** [perlin-network/wavelet#221]
Build fails on 32 bit raspberry pi from source archive `wavelet-0.1.1`

The relevant error is:

```
...
# github.com/perlin-network/wavelet/avl
avl/node.go:371:17: constant 4294967295 overflows int
package main
avl/node.go:379:19: constant 4294967295 overflows int
avl/node.go:519:16: constant 4294967295 overflows int
avl/node.go:529:19: constant 4294967295 overflows int
```

The problem is that `len` returns a platform independent `int`.

Removing the checks:
```go
if len(n.key) > math.MaxUint32 {
    panic("avl: key is too long")
}
```
lets the build to succeed, though I imagine you'll want to find a platform independent way to keep those assertions.

**Comment by rkeene** [comment]
This has been fixed as part of the work in #321 which has been merged to master and will be included in the next release.  Additionally, a 32-bit build is tested during CI.
