### ISSUE TITLE
Wavelet status - wrong addresses in peers table 

### ISSUE THREAD

**Issue by a-urth** [perlin-network/wavelet#227]
If node is disconnected (shut down) wavelet's peer table still will show this address. This is intended behavior since we don't know when this node will get up so we still should consider it as a peer.
Then if node is connected again with same public key but with different IP address, on target node in peers table this public address is present, in single instance but with old IP address.

Expected: node should be present in peers table but with new address.

Note: this is not the case if node is getting manually disconnected with either api or cli methods. Because in this case it gets removed from node's peer table.

**Comment by a-urth** [comment]
thats a noise issue, will be fixed in that respectively

**Comment by a-urth** [comment]
https://github.com/perlin-network/noise/pull/240

**Comment by rkeene** [comment]
Merged in #231
