### ISSUE TITLE
panic: avl: could not find node

### ISSUE THREAD

**Issue by rkeene** [perlin-network/wavelet#238]
```
panic: avl: could not find node cc17901df20f06d798e5a553a00d6c1a

goroutine 48 [running]:
github.com/perlin-network/wavelet/avl.(*Tree).mustLoadNode(...)
        /src/avl/tree.go:297
github.com/perlin-network/wavelet/avl.(*Tree).mustLoadLeft(0xc0017baba0, 0xc000287290, 0xc000f894a8)
        /src/avl/tree.go:332 +0xbb
github.com/perlin-network/wavelet/avl.(*node).lookup(0xc000287290, 0xc0017baba0, 0xc000042060, 0x22, 0x30, 0x22, 0xffffffffffffffff, 0xc000287170, 0x0)
        /src/avl/node.go:246 +0xf6
github.com/perlin-network/wavelet/avl.(*node).lookup(0xc000287170, 0xc0017baba0, 0xc000042060, 0x22, 0x30, 0x22, 0x1, 0xc000286f30, 0x0)
        /src/avl/node.go:249 +0x18d
github.com/perlin-network/wavelet/avl.(*node).lookup(0xc000286f30, 0xc0017baba0, 0xc000042060, 0x22, 0x30, 0x22, 0xffffffffffffffff, 0xc000286e10, 0x0)
        /src/avl/node.go:251 +0x221
github.com/perlin-network/wavelet/avl.(*node).lookup(0xc000286e10, 0xc0017baba0, 0xc000042060, 0x22, 0x30, 0x22, 0x1, 0x0, 0x203000)
        /src/avl/node.go:249 +0x18d
github.com/perlin-network/wavelet/avl.(*node).lookup(0xc000032090, 0xc0017baba0, 0xc000042060, 0x22, 0x30, 0x30, 0x40de26, 0xc000042060, 0xc000042060)
        /src/avl/node.go:251 +0x221
github.com/perlin-network/wavelet/avl.(*Tree).Lookup(0xc0017baba0, 0xc000042060, 0x22, 0x30, 0x22, 0xc000042060, 0x1, 0x30)
        /src/avl/tree.go:99 +0x5b
github.com/perlin-network/wavelet.readUnderAccounts(0xc0017baba0, 0xe6e1c5a99ef1a568, 0x9f155a1789a13618, 0x589eeb073c27dc36, 0x18327e9529358b44, 0x14a926e, 0x1, 0x1, 0xc0017baba0, 0xbffe70, ...)
        /src/db.go:258 +0xf1
github.com/perlin-network/wavelet.ReadAccountStake(0xc0017baba0, 0xe6e1c5a99ef1a568, 0x9f155a1789a13618, 0x589eeb073c27dc36, 0x18327e9529358b44, 0x0, 0x0)
        /src/db.go:149 +0x64
github.com/perlin-network/wavelet.CollectVotesForSync(0xc000194240, 0xc00019a1c0, 0xc00025ade0, 0xc0000ba690, 0x2)
        /src/vote.go:64 +0x4c2
created by github.com/perlin-network/wavelet.(*Ledger).SyncToLatestRound
        /src/ledger.go:908 +0x11e
```

**Comment by rkeene** [comment]
This happened on restart so apparently we are not flushing the AVL tree atomically somewhere.

Temporary work around is to wipe the DB when this case is detected (manually).  This workaround has been added to Wavelet-Stack.

We can also have the node optionally wipe the database when this condition is hit, so on next restart it will resync and start working.

The solution is to track down where the atomic update of the AVL to DB isn't happening and fix it

**Comment by a-urth** [comment]
@losfair didn't we have this issue before? did we come to some sort of resolution last time?

**Comment by losfair** [comment]
Solution to this would be a graceful shutdown (to ensure no write to the avl tree is happening, and the backing database is fully synced).

**Comment by a-urth** [comment]
yes, but what if the process is simply killed? thats actually what happened here

**Comment by losfair** [comment]
Graceful shutdown requires handling of `SIGINT` and `SIGTERM` at least. Those two signals cover most of the cases where a process is "killed".

**Comment by a-urth** [comment]
ok, what if computer manually shut down?)
i mean, don't you think we need some backup plan to check whether db is corrupted or not?
someone can manually mess it as well

**Comment by a-urth** [comment]
or just deleting db files/folder would be a "solution" in that case?

**Comment by AhmadMuzakkir** [comment]
PR #244

**Comment by rkeene** [comment]
I haven't seen this issue since we've implemented graceful shutdown and reduced the amount of restarts needed.  I'm going to close this out and if we have the issue again we can resume looking into it.
