### ISSUE TITLE
--wallet not working

### ISSUE THREAD

**Issue by danielding3** [perlin-network/wavelet#245]
```./wavelet-darwin-amd64 --port 3000 --api.port 9000 --wallet 67724480df7c62815c9891fd50492ea1b589df130a072db09afc664431a76f6e12eaa2f2688b8eb9cd64aa293378b6adce7d63bae070f8995e84e73da6ed745c 1.2.3.4:3000 
5:47PM INF Listening for peers. addr: 127.0.0.1:3000
panic: the private key specified is invalid: 67724480df7c62815c9891fd50492ea1b589df130a072db09afc664431a76f6e12eaa2f2688b8eb9cd64aa293378b6adce7d63bae070f8995e84e73da6ed745c

goroutine 1 [running]:
main.start(0xc0002bd0a8, 0x1b25580, 0xc0000a2000, 0x1b1d3c0, 0xc00000e010)
	/home/rkeene/devel/perlin-dev/wavelet/cmd/wavelet/main.go:334 +0x17d3
main.Run.func3(0xc0002a0160, 0x0, 0x0)
	/home/rkeene/devel/perlin-dev/wavelet/cmd/wavelet/main.go:274 +0x779
gopkg.in/urfave/cli%2ev1.HandleAction(0x18757c0, 0xc0002728d0, 0xc0002a0160, 0x0, 0x0)
	/home/rkeene/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0xc8
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc00029e000, 0xc000030080, 0x8, 0x8, 0x0, 0x0)
	/home/rkeene/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x590
main.Run(0xc000030080, 0x8, 0x8, 0x1b25580, 0xc0000a2000, 0x1b1d3c0, 0xc00000e010, 0xc00007e000)
	/home/rkeene/devel/perlin-dev/wavelet/cmd/wavelet/main.go:282 +0x1859
main.main()
	/home/rkeene/devel/perlin-dev/wavelet/cmd/wavelet/main.go:75 +0x7b
```
It doesn't work when using the path for the private-key either.

**Comment by AhmadMuzakkir** [comment]
The error is because the key has invalid prefixed zero bits.

If you want to generate new key, don't pass the `--wallet` flag.
A new key will be generated for you.

**Comment by danielding3** [comment]
Thanks Ahmad,
Is this able to be connected to the key generated from lens.perlin.net? That's where I sourced the private key used from.

**Comment by AhmadMuzakkir** [comment]
Yes, you can use key to login on lens.

When you don't pass the `--wallet` flag, a new key will be generated and logged on the output.

e.g.
![image](https://user-images.githubusercontent.com/10398517/65946925-c5a2f180-e469-11e9-8a94-bd55f2867342.png)

The `privateKey` value is your private key.

You can copy the key and paste it on lens.

**Comment by hasyimibhar** [comment]
Hmm, weird, happening to me as well. I can't use the key generated from lens on master branch. This is the key I'm using: `02c1501edb7c1590024121d488463e70cbbfb6e435e94a3f6915d465f1ca318e2f5022f962070be13d7989c741e758d649a0ae7634cb100055fef271e7fde368`.

I'm guessing it's something to do with different config?

**Comment by hasyimibhar** [comment]
Using PR #246, I'm getting the following error: `keys are invalid: failed to pass static puzzle as prefix length of checksum is 0, yet c1 is 1`.

**Comment by AhmadMuzakkir** [comment]
Issue #252.
