### ISSUE TITLE
Lens' generated private cannot be used to run Wavelet

### ISSUE THREAD

**Issue by AhmadMuzakkir** [perlin-network/wavelet#252]
Referring to issue #245.

Lens generate private key that has prefixed zero bits of 0.

This will cause issue if you use the key to run Wavelet, since the Wavelet's SKademlia requires the private key to have 1 prefixed zero bits (C1).

<br />

The possible solutions are:
- Update Lens and/or Wavelet to make C1 to match. 
Note: If we make Lens to fulfil the C1, it'll increase CPU usage of the Lens server. 

- Make C1 configurable, and have the user pass the correct value of C1.

**Comment by iwasaki-kenta** [comment]
Let's redirect this issue over to Lens rather in Wavelet.
