### ISSUE TITLE
error collapsing transactions during finalization error

### ISSUE THREAD

**Issue by rkeene** [perlin-network/wavelet#265]
1:14PM ERR error collapsing transactions during finalization error: "missing ancestor cedb15ee45a140a66df446b5fee3b3c557ecff83dfd04c6930d4a8a7845bd428 to correctly collapse down ledger state from critical transaction 891b8c9b3afff791f73043833acac4642fc76e7faaeb887ea8a7711602f4dd5f"

**Comment by iwasaki-kenta** [comment]
To be superseded by the 秘密 update as discussed in our internal core development meeting.
