### ISSUE TITLE
Transactions disappear from Lens

### ISSUE THREAD

**Issue by Asim-Sheikh** [perlin-network/wavelet#268]
Transactions seem to be disappearing from Lens. They appear for sometime but some time later would not be listed anymore. I have seen this with Staking transactions (might be true for others as well but havent tested).  To reproduce:

- Create account using wavelet node
- Login on Lens
- Stake some PERLS. It should now be listed under transactions on the Validator page as well as Dashboard.
- Wait for sometime
- Refresh the page and it will be gone

**Comment by iwasaki-kenta** [comment]
Please refer to my comment here https://github.com/perlin-network/wavelet/issues/269#issuecomment-540398009 as the likely cause for the issue is most probably related.

**Comment by Asim-Sheikh** [comment]
ok this

> Please refer to my comment here [#269 (comment)](https://github.com/perlin-network/wavelet/issues/269#issuecomment-540398009) as the likely cause for the issue is most probably related.

Might be worth reopening this as its happening on testnet.perlin.net and not my local node.

https://lens.perlin.net/#/transactions/1f9ecc94ab6a9c13b21fcd6a3ecccfadc7cbd8daa70894d02f21c329407b3250

https://lens.perlin.net/#/transactions/18da14ffc4cc30ca46bab6092fcfeb5a76a751e4455a463ff5957e4878572ee4


These are staking transactions that were successful and stake amount is correctly shown on Lens (connected to testnet.perlin.net). These transactions were initial shown on the Validator page and showed the details when opening the details page linked above. However now they are not listed on Validator page and links above report 404. The stake is stilla ctive however and correct values are shown.

Account public key: 405c26514497ea02badd3ac5e6e9f9ada353dfa7604ddc418901acdda562ad08

**Comment by Asim-Sheikh** [comment]
Here is another transaction that disappeared initiated from the same account but this time it was initiated at the local node: 
`{
id: "5a9acf9c8a8b7afa182692a5275f40efe7d62950ac62ce9cf8e20c8c1541739c",
sender: "405c26514497ea02badd3ac5e6e9f9ada353dfa7604ddc418901acdda562ad08",
creator: "405c26514497ea02badd3ac5e6e9f9ada353dfa7604ddc418901acdda562ad08",
status: "applied",
nonce: 0,
depth: 681158072,
tag: 3,
payload: "ARAnAAAAAAAA",
sender_signature: "226b2d624f6c83b516bc19ed21266db27f13da242f95eec973c8a759d9e612759b70542ac333f769cdb986f9d840b0130f9d233129e22e7181871cc7d22b0a0b",
creator_signature: "226b2d624f6c83b516bc19ed21266db27f13da242f95eec973c8a759d9e612759b70542ac333f769cdb986f9d840b0130f9d233129e22e7181871cc7d22b0a0b",
parents: [
"070813399c5c25c1fe3f9c38fcdbab34344ccbb02d82483ba27550bac0d19672"
]
}`

**Comment by rkeene** [comment]
@Asim-Sheikh For this issue, I believe this is expected.  The current testnet prunes the database of transactions that occurred more than `conf.pruningLimit` (30; https://github.com/perlin-network/wavelet/blob/3baf2e86dc3ceda123cd76a3fae59b8437bcc374/conf/conf.go#L41-L42) "rounds" ago, while the effect of the transaction is carried forward the specific transaction is no longer needed as a sufficient number of nodes have validated the data.

**Comment by Asim-Sheikh** [comment]
@rkeene That is good to know. What is the plan for mainnet? surely the Node used for Lens should not be pruning them?
