### ISSUE TITLE
Support in-memory BadgerDB

### ISSUE THREAD

**Issue by rkeene** [perlin-network/wavelet#333]
As a part of #326 we added support for BadgerDB as a backend, however it requires an on-disk database to be specified.  We should add support for an in-memory-only option, either by using LevelDB in memory or by supporting BadgerDB in memory.

There is some discussion around BadgerDB memory support here: dgraph-io/badger#377

Temporarily I've switched the default back to LevelDB.

**Comment by AhmadMuzakkir** [comment]
PR #336 fixed this issue.
