### ISSUE TITLE
Investigate why `sys/const.go` `GasTable` is not currently used.

### ISSUE THREAD

**Issue by a-urth** [perlin-network/wavelet#340]

**Comment by rkeene** [comment]
Seems to be commented out in contract.go:
https://github.com/perlin-network/wavelet/blob/65877aca9d15ebf52bc61224a04093f8b5e72cff/contract.go#L107-L115

**Comment by iwasaki-kenta** [comment]
`GasTable` will be re-used when we figure out the economics for smart contract fees.
