### ISSUE TITLE
Investigate `ConnectDisconnect` test problem.

### ISSUE THREAD

**Issue by a-urth** [perlin-network/wavelet#341]
`ConnectDisconnect` test in `main_test.go` currently hangs indefinitely if running with all other tests.
By initial investigation I found that grpc server is not shutting down. Current assumption is that there is open connection somewhere which is not being closed. Since we use `grpc.GracefulShutdown` which waits for all connection to be resolved, and changing it to `Shutdown` which drops all connections resolves issue. Suspected is `noise.skademlia.connLoop` which is goroutine which cannot be shutdown externally and it finalizes itself only after certain amount of time.

**Comment by a-urth** [comment]
Problem was in `UpdateParams` test which changed configuration for all follow up tests, and connect-disconnect one was the only one.

**Comment by rkeene** [comment]
Fixed in #355
