### ISSUE TITLE
Update Code Style Guide to Include Linting Guides

### ISSUE THREAD

**Issue by rkeene** [perlin-network/wavelet#348]
As part of #346 there was a question about when `nolint` should be used and I provided some guidance there, but it would be good if the Code Style Guide and Code Review Guide could be updated to consider how we deal with linting.

**Comment by a-urth** [comment]
@hasyimibhar i'll ask you question here real quick and then update our guide.
Nolints are mostly used now for existing code, to not interfere with already existing PRs. Especially lints like gocyclo and gocognit which will require a lot of effort to resolve (in most cases). So its fine to add nolints now to merge opened PRs and maybe open issue about refactoring.
For all new code though, errors from those linters responsible for code complexity should be taken as a strong advice to restructure new code. And nolints can be added only in case of strong arguments why it cannot or shouldn't be changed.

**Comment by a-urth** [comment]
https://app.nuclino.com/Perlin/Perlin-Homebase/-Code-Style-473d34bd-c1a8-409d-b33f-0ec19ab65129

**Comment by a-urth** [comment]
@rkeene this can be closed i guess?

**Comment by rkeene** [comment]
Yep !
