### ISSUE TITLE
Fix transaction syncing after state sync.

### ISSUE THREAD

**Issue by a-urth** [perlin-network/wavelet#395]
There is problem with double spending after state syncing.
Imagine node which getting restarted without having database.
After syncing state it'll start syncing transactions and since it'll have current block but none of the transactions it'll sync all of the previously applied transactions.
Then it'll get them into block and start proposing it. Since other nodes already have those transaction in some circumstances they may vote in favor of that block and finalize it.
This will result into transactions previously applied being applied again.

I'm not sure that there is an easy solution aside using db always (considering #382 is done).

**Comment by iwasaki-kenta** [comment]
After state syncing, we should have received roughly what the majority of nodes believe is the latest block _B_.

None of the nodes should finalize block _B_ ever again because block _B_ either:
1) the nodes have a different block stored at block _B_'s height.
2) the nodes already have block _B_.
3) the block is at a height that should have already been pruned away.

A change to transaction syncing needs to be done. Now that we have all transactions stored in the database as well, what should happen is that upon state syncing, we also download transactions for block _B_.

**Comment by a-urth** [comment]
Block B won't be finalized again, I was saying that it would be new block containing already applied transactions.
Downloading transactions just for block B (block received from syncing) won't help since there are transactions for at least `syncAfterBlock` and at most `pruningLimit`-1 blocks more, which will be synced and restarted node is not aware about whether they are new or already have been applied.
We can to not download transactions from block B by explicitly adding them to sync tx index, or download them without adding to proposal index, since we know that they are already in finalized block, but we need to do the same for previous `pruningLimit` number of blocks as well.
Alternatively we need to change how we sync transactions - sync separately ones in finalized blocks and ones which are "new". But nonetheless we'll need to sync previous blocks before block B as well.

**Comment by iwasaki-kenta** [comment]
> Block B won't be finalized again, I was saying that it would be new block containing already applied transactions.
> Downloading transactions just for block B (block received from syncing) won't help since there are transactions for at least `syncAfterBlock` and at most `pruningLimit`-1 blocks more, which will be synced and restarted node is not aware about whether they are new or already have been applied.
> We can to not download transactions from block B by explicitly adding them to sync tx index, or download them without adding to proposal index, since we know that they are already in finalized block, but we need to do the same for previous `pruningLimit` number of blocks as well.
> Alternatively we need to change how we sync transactions - sync separately ones in finalized blocks and ones which are "new". But nonetheless we'll need to sync previous blocks before block B as well.

Wouldn't the transactions in block _B_ have a block height that is too old, such that they can't be used to propose a new block?

**Comment by a-urth** [comment]
In block B transactions actually will be to new to propose, since we do not update `Transactions.height` after syncing, which I guess a bug.
Block B contains only newest transactions, are you talking about transactions before block B, aren't they too old?

**Comment by iwasaki-kenta** [comment]
> In block B transactions actually will be to new to propose, since we do not update `Transactions.height` after syncing, which I guess a bug.
> Block B contains only newest transactions, are you talking about transactions before block B, aren't they too old?

Oh my bad (right, we should update `(*Transactions).height` after state syncing as well).

In this case, we might actually want to consider changing up your syncing strategy a bit in general then to perhaps syncing up the last `current.height - pruning_limit` blocks. Upon finalizing state syncing, we should then also have all the transactions of these last few blocks and add them in an index to ensure we don't ever download them or use them to propose a new block.

This is a relatively large refactor however, though this would actually improve the security of our state syncing strategy realistically.

What do you think?

**Comment by a-urth** [comment]
Pulling all blocks within pruning limit during sync state should work. Although still we'll need to change either how we sync transactions or how we add them in order to distinguish ones which are finalized and ones which are not.
