### ISSUE TITLE
Syncing contract transaction results into grpc stream error.

### ISSUE THREAD

**Issue by a-urth** [perlin-network/wavelet#417]
If there is syncing of smart contract transaction after state sync (i.e. node restarted) there is rpc stream error which is never recovered.

**Comment by a-urth** [comment]
There are two problems here:
1. Actual rpc error is because provider of syncing transactions assumes that requester got all of the transactions and returns nil response, so next header send has no receiver and results into EOF error. Logging message was incorrect due to copy paste error.
2. But this issue occurs in the first place because contract transaction is considered invalid and just skipped so it cannot be synced at all. And there was no logging message to that because only signature validation error was logged for some reason. And contract transaction was considered invalid because validation for contracts check whether such contract exists in the memory and since we sync state before transaction its getting download and thus far exists.

Resolution is to skip this particular error, since this transaction needs to be added to buffer anyway. Now there will be another error - application error, since this contract was already applied, but thats fine for now, since this issue will be resolved in corresponding PR about double spending.

**Comment by a-urth** [comment]
@ryanswart @iwasaki-kenta fyi

**Comment by iwasaki-kenta** [comment]
Awesome work, merged in the PR - thanks :smile:.
