### ISSUE TITLE
Re-evaluate how to consider whether or not a transaction that is gossiped is successful.

### ISSUE THREAD

**Issue by iwasaki-kenta** [perlin-network/wavelet#68]
Right now, if less than alpha * K peers consider a transaction you gossip to not be correct, your node will consider your transaction to have failed.

Out of the K peers that you gossip to however, it is possible that a small number of those peers have considered your transaction to be correct. If so, and they or their neighboring peers create a critical transaction, your transaction by the end of the consensus round would have been accepted.

One option is to overall consider gossiping successful if any single peer out of your K peers considers your transaction correct, and to notify whether or not the transaction in the end was accepted/rejected by the time the consensus round ends.

Additionally, should gossiping for a single transaction fail, it would be good to retry gossiping a number of times by having a circular buffer of transactions to retry resending.

**Comment by a-urth** [comment]
@iwasaki-kenta is this issue still relevant?

**Comment by iwasaki-kenta** [comment]
To be superseded by the 秘密 update as discussed in our internal core development meeting.
